# Generated by Django 4.2 on 2023-04-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_name', models.CharField(max_length=100)),
                ('pack_duration', models.CharField(max_length=100)),
                ('pack_price', models.IntegerField()),
                ('pack_details', models.TextField()),
                ('day_pickup', models.CharField(max_length=100)),
            ],
        ),
    ]
