# Generated by Django 4.2 on 2023-04-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('ui_text', models.CharField(max_length=100)),
            ],
        ),
    ]
