# Generated by Django 4.2 on 2023-04-14 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delivery_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_picked', models.DateTimeField()),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.delivery_status')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_member')),
            ],
        ),
    ]
